### ISSUE TITLE
No work with Altay?

### ISSUE THREAD

**Issue by usser1976** [MasApip/DisguisePlugin#1]
Altay Crash Dump Tue Mar 16 15:03:20 CET 2021

Error: syntax error, unexpected 'Main' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
File: plugins/DisguisePlugin_dev-3.phar/src/ArasakaID/Disguise/Main
Line: 25
Type: ParseError

THIS CRASH WAS CAUSED BY A PLUGIN

Code:

Backtrace:
#0 pmsrc/vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[23] ArasakaID\Disguise\Main)
#1 (): BaseClassLoader->{closure}(string[23] ArasakaID\Disguise\Main)
#2 (): spl_autoload_call(string[23] ArasakaID\Disguise\Main)
#3 pmsrc/src/pocketmine/plugin/PluginManager(167): class_exists(string[23] ArasakaID\Disguise\Main, boolean 1)
#4 pmsrc/src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[49] /home/minecraft/plugins/DisguisePlugin_dev-3.phar, array[3])
#5 pmsrc/src/pocketmine/Server(1606): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/minecraft/plugins/)
#6 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
#7 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
#8 pmsrc(11): require(string[63] phar:///home/minecraft/altay.phar/src/pocketmine/PocketMine.php)

Altay version: 3.18.1+dev [Protocol 428]

**Comment by ArasakaID** [comment]
this plugin only supported php 7.4 or higher, update your php bin
