### ISSUE TITLE
No plugin response

### ISSUE THREAD

**Issue by ghost** [MasApip/DisguisePlugin#5]
Hello, I downloaded your plugin and joined my server. I ran the command /disguise and I saw the command syntax but I tried many methods on running the command but I get no feedback. I get no error messages, no error syntax within console..etc.

Also [_below_] shows the plugin loaded without error

`[19:36:45] [Server thread/INFO]: Loading Disguise v1.0.2`

**Comment by ArasakaID** [comment]
https://youtu.be/oM9EcAr5_JY, Are you really using the command? watch this video for how to use it.
