### ISSUE TITLE
Server is crashing randomly

### ISSUE THREAD

**Issue by JoshuaPHYT** [MasApip/DisguisePlugin#8]
Error: Too few arguments to function ArasakaID\Disguise\entity\Entity::__construct(), 2 passed in phar:///home/container/PocketMine-MP.phar/src/pocketmine/entity/Entity.php on line 381 and exactly 3 expected
File: plugins/DisguisePlugin.phar/src/ArasakaID/Disguise/entity/Entity
Line: 19
Type: ArgumentCountError

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Disguise v1.0.2

**Comment by ArasakaID** [comment]
Check Update 1.0.3 !
